version: "3"

tasks:
  dev: 
    cmds:
      - go run main.go
    desc: Run the application in development mode
  build:
    cmds:
      - go build -o bin/app
    desc: Build the application

  run:
    cmds:
      - bin/app
    desc: Run the application
